# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    # Note: custom_lint reads rule options as sibling keys of the rule name.
    - architecture_imports:
      config: tool/lints/architecture_lints.yaml
    - modal_entrypoints:
      include:
        - lib/**
      allow_prefixes:
        - lib/core/adaptive/widgets/
    - hardcoded_ui_colors:
      include:
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
      allow:
        - Colors.transparent
    - hardcoded_font_sizes:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - manual_text_scaling:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - spacing_tokens:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - radius_tokens:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - state_opacity_tokens:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - motion_durations:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - icon_size_tokens:
      include:
        - lib/core/adaptive/widgets/**
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
    - restricted_imports:
      include:
        - lib/**
      rules:
        - uri: package:dio/dio.dart
          allow:
            - lib/core/network/**
          message: Use `lib/core/network/**` wrappers (ApiClient/ApiHelper).
        - uri: package:firebase_analytics/firebase_analytics.dart
          allow:
            - lib/core/services/analytics/**
          message: Use analytics wrappers under `lib/core/services/analytics/**`.
        - uri: package:firebase_crashlytics/firebase_crashlytics.dart
          allow:
            - lib/core/services/early_errors/**
            - lib/core/utilities/log_utils.dart
            - lib/core/di/**
          message: Use crash reporting wrappers under `lib/core/services/early_errors/**`.
        - uri: package:firebase_messaging/firebase_messaging.dart
          allow:
            - lib/core/services/push/**
            - lib/main*.dart
          message: Use push wrappers under `lib/core/services/push/**`.
        - uri: package:shared_preferences/shared_preferences.dart
          allow:
            - lib/core/services/**
            - lib/features/user/data/datasource/local/profile_draft_local_datasource.dart
            - lib/features/user/data/datasource/local/profile_avatar_cache_local_datasource.dart
          message: Use shared preferences only in stores/services; avoid direct usage in most features.
        - uri: package:flutter_secure_storage/flutter_secure_storage.dart
          allow:
            - lib/core/storage/secure/**
          message: Use secure storage wrappers under `lib/core/storage/secure/**`.
        - uri: dart:developer
          allow:
            - lib/core/utilities/log_utils.dart
          message: Use `Log.*` helpers from `lib/core/utilities/log_utils.dart`.
    - hardcoded_ui_strings:
      include:
        - lib/core/widgets/**
        - lib/features/**
        - lib/navigation/**
        - lib/presentation/**
      exclude:
        - lib/core/dev_tools/**
        - "**/*showcase*"
    - route_string_literals:
      include:
        - lib/navigation/**
        - lib/features/**
        - lib/presentation/**
    - api_helper_datasource_policy:
      include:
        - lib/features/*/data/datasource/**
      require_requires_auth: true

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    directives_ordering: true
    always_use_package_imports: true
    cancel_subscriptions: true
    close_sinks: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
