core: https://prod-core.example.com/api
auth: https://prod-auth.example.com/api
profile: https://prod-profile.example.com/api
enableLogging: false
reminderExperiment: false

# Analytics
analyticsEnabledDefault: true
analyticsDebugLoggingEnabled: false

# Google OIDC (Sign-In)
googleOidcServerClientId: <your-google-web-client-id>.apps.googleusercontent.com

# Network logging (console-only)
netLogMode: off
netLogBodyLimitBytes: 8192
netLogLargeThresholdBytes: 65536
netLogSlowMs: 800
netLogRedact: true
